server:
  port: 8080


spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC

#  aop:
#    auto: true
#    proxy-target-class: true

  redis:
    host: localhost
    port: 6379
    password: 123456
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

